import React,{useMemo,useState}from'react';import{BrainCircuit,BookOpen,FlaskConical,Layers,Library,BarChart3,Users,Search,ShieldCheck,ExternalLink,ArrowLeft,Target,AlertTriangle,CheckCircle2,Menu,X}from'lucide-react';import{motion}from'framer-motion';import{pocs,useCases}from'./data/catalog.js';
const modules=[['playbook','AI Playbook','Governance, recipes, learning path and roadmap',BookOpen],['pocs','Team POCs','Evidence, KPI, risks and scale gates',FlaskConical],['usecases','Use Case Catalog','Twelve reusable governed workflows',Layers],['registry','Prompt Registry','Versioned program prompt metadata',Library],['dashboard','Adoption Dashboard','Value, quality, adoption and risk',BarChart3],['community','Community','Contribution and lessons learned',Users]];
function App(){const[page,setPage]=useState('home'),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[open,setOpen]=useState(false);const filtered=useMemo(()=>useCases.filter(x=>(x.id+x.name+x.domain+x.maturity).toLowerCase().includes(q.toLowerCase())),[q]);const go=x=>{setPage(x);setSelected(null);setOpen(false);scrollTo({top:0,behavior:'smooth'})};return <div><header><button className="brand" onClick={()=>go('home')}><BrainCircuit/> <span><b>AI Test Manager Hub</b><small>Governed • Measurable • Human reviewed</small></span></button><nav>{[['home','Home'],...modules.map(x=>[x[0],x[1]])].map(([id,n])=><button className={page===id?'active':''} onClick={()=>go(id)} key={id}>{n}</button>)}</nav><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobileNav">{modules.map(x=><button onClick={()=>go(x[0])}>{x[1]}</button>)}</div>}
{page==='home'&&<><section className="hero"><div><span className="pill">AI Test Management Program</span><h1>Turn approved AI content into an operating QA capability.</h1><p>One entry point for the Playbook, POC evidence, use cases, prompt governance, measurement, risk controls and adoption.</p><button onClick={()=>go('usecases')}>Explore use cases</button></div><div className="heroCard"><h3><ShieldCheck/> Program boundaries</h3><p><b>Playbook:</b> program-owned knowledge</p><p><b>POCs:</b> team-owned evidence</p><p><b>Prompts:</b> named owner and version</p><p><b>Hải's library:</b> external reference only</p></div></section><main><h2>Program modules</h2><div className="grid">{modules.map(([id,n,d,I],i)=><motion.button initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="card module" onClick={()=>go(id)}><I/><h3>{n}</h3><p>{d}</p></motion.button>)}</div></main></>}
{page==='pocs'&&<Page title="Team POC Catalog" back={()=>go('home')}>{!selected?<div className="grid three">{pocs.map(p=><button className="card left" onClick={()=>setSelected(p)}><span className="pill">{p.id} • {p.stage}</span><h3>{p.name}</h3><p>{p.target}</p><small>{p.uses.join(' • ')}</small></button>)}</div>:<Detail title={selected.name} badge={`${selected.id} • ${selected.stage}`} back={()=>setSelected(null)} sections={[['Target',selected.target],['Use cases',selected.uses.join(', ')],['Primary risk',selected.risk],['Mandatory control',selected.control]]}/>}</Page>}
{page==='usecases'&&<Page title="AI Use Case Catalog" back={()=>go('home')}>{!selected?<><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ID, name, domain or maturity"/></label><div className="grid three">{filtered.map(u=><button className="card left" onClick={()=>setSelected(u)}><span className="pill">{u.id} • {u.maturity}</span><h3>{u.name}</h3><p>{u.domain}</p><small>{u.prompt}</small></button>)}</div></>:<Detail title={selected.name} badge={`${selected.id} • ${selected.maturity}`} back={()=>setSelected(null)} sections={[['Domain',selected.domain],['Prompt Registry ID',selected.prompt],['KPI and target',selected.kpi],['Primary risk',selected.risk],['Mandatory control',selected.control]]}/>}</Page>}
{page==='registry'&&<Page title="Prompt Registry" back={()=>go('home')}><p className="lead">The website shows metadata only. Complete prompt text remains separately controlled and versioned.</p><div className="tableWrap"><table><thead><tr><th>ID</th><th>Use case</th><th>Status</th><th>Owner/approval</th></tr></thead><tbody>{useCases.map(u=><tr><td>{u.prompt}</td><td>{u.id} {u.name}</td><td>{u.maturity}</td><td>Named prompt owner + qualified reviewer</td></tr>)}</tbody></table></div></Page>}
{page==='dashboard'&&<Page title="Adoption Dashboard" back={()=>go('home')}><div className="grid four">{[['Accuracy','≥90% mapped output'],['Efficiency','≥30% POC-01; ≥40% POC-03'],['Governance','0 critical unresolved incidents'],['Scale','≥80/100 weighted POC score']].map(x=><div className="card metric"><Target/><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="card content"><h3>Dashboard specification</h3><p>Track baseline hours, AI-assisted hours, review effort, accepted output, mapping, incidents, active users, overdue prompt reviews and scale status. All metrics require an explicit denominator and source system.</p></div></Page>}
{page==='playbook'&&<Page title="AI Playbook" back={()=>go('home')}><div className="card content"><h3>Official training and operating material</h3><p>Download the full Word document from <code>docs/AI_Playbook_for_Test_Managers_Complete.docx</code>.</p><a href="./docs/AI_Playbook_for_Test_Managers_Complete.docx" download>Download Playbook</a></div></Page>}
{page==='community'&&<Page title="Community and References" back={()=>go('home')}><div className="grid three">{[['Contribution','Owner, source, version, reuse permission and reviewer are mandatory.'],['Lessons Learned','Record context, result, failure mode, corrective action and evidence.'],['Hải’s Prompt Library','Independent contributor-owned reference; do not copy prompt content without approval.']].map(x=><div className="card content"><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div><a className="external" href="https://lhlhai.github.io/prompt-library/" target="_blank" rel="noreferrer">Open external Prompt Library <ExternalLink/></a></Page>}
<footer>AI Test Manager Hub • Human-reviewed • Ownership-aware</footer></div>}
const Page=({title,back,children})=><main><button className="back" onClick={back}><ArrowLeft/> Back to Hub</button><h1 className="pageTitle">{title}</h1>{children}</main>;
const Detail=({title,badge,back,sections})=><><button className="back" onClick={back}><ArrowLeft/>Back</button><div className="card detail"><span className="pill">{badge}</span><h2>{title}</h2><div className="detailGrid">{sections.map(([a,b])=><div><h4>{a}</h4><p>{b}</p>{a.includes('risk')?<AlertTriangle/>:<CheckCircle2/>}</div>)}</div></div></>;
export default App;
